### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by PierrePontic** [jmmorato/openddsharp#38]
Hello, I'm trying to test my test program on another computer than the one I use to build.

In that case my application run and return immediatly. No error message, even lauched with prompt. (that's a WPF application). If it was a .NET framework version issue, I would get a messagebox asking me to install the newest framework version. (I tried it on another computer).

So, I remind that to build an OpenDDSharp project, I needed to install Window SDK 10.0.16299.0, and in the event log of window, I got that message : 
```
Faulting application name: HelloWorldSubscriber.exe, version: 1.0.0.0, time stamp: 0x5ff2e2a8
Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x1854
Faulting application start time: 0x01d70ec3e840cd63
Faulting application path: C:\Users\Sonovein.DESKTOP-KCU7HGU\Desktop\HelloWorldSubscriber\Debug\HelloWorldSubscriber.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 64ce5a57-cc89-44a0-b0dd-7fcac6c547f3
Faulting package full name: 
Faulting package-relative application ID: 
```

No error, that's my application. We can see : "Faulting module name: KERNELBASE.dll, version: 10.0.19041.207", I guess that's the problem.

Would you confirm ? What should I install on the target computer to solve that issue ? (I can't install visualstudio on that machine)

**Comment by jmmorato** [comment]
Did you install the VC++ redistributable on that machine? https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by PierrePontic** [comment]
I installed it, without improvement. I just tried to launch Dependencies (a .net reboot of dependency walker), that have nothing to do with OpenDDSharp, that works fine on my computer, but return the same way as my first test.
```
Nom de l’application défaillante DependenciesGui.exe, version : 1.10.0.0, horodatage : 0x603e0eb3
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.207, horodatage : 0x746c1866
Code d’exception : 0xe0434352
Décalage d’erreur : 0x0000000000023e49
ID du processus défaillant : 0xbc4
Heure de début de l’application défaillante : 0x01d70f4cdcea38d8
Chemin d’accès de l’application défaillante : C:\Users\Sonovein.DESKTOP-KCU7HGU\Desktop\DependenciesReleasex64\DependenciesGui.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 4eb3e2a1-5905-4581-82ec-95fffd2e21ad
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
```

**Comment by PierrePontic** [comment]
I just found another error related to mmy executable, and I can't understand why there is a reference to the framework v4.0.30319, because my project is made with .NET v4.7.2
```
Application: TestSubscriber.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotImplementedException
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType, Int16)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at System.Windows.Application.Run()
   at TestSubscriber.App.Main()
```

Any idea ?

**Comment by jmmorato** [comment]
Difficult to say without debugging the actual project...

With just the information provided, I would say it is a dependency redirection issue, two libraries of your project have the same dependency but requiring different versions. If so, that could be easily fixed with a binding redirection in your app.config but as I said before not enough info to figure it out.

**Comment by PierrePontic** [comment]
Thank you for your time, I'm multiplying test on different computers at my place, it's look like there is no relation between the problem and openDDSharp dependencies, I close this issue.

**Comment by PierrePontic** [comment]
Hello, I didn't found exactly why, but I identified how to deploy my OpenDDSharp test application on another computer : the minimum component to install are found in the vs2019 installer : 
- MSVC v142 - VS 2019 x64/x86 Build Tools (latest version)
- Windows 10 SDK (10.0.19041.0)

here is an importable configuration file for vs_installer 2019
[vsInstallForOpenDDSharp.zip](https://github.com/jmmorato/openddsharp/files/6077932/vsInstallForOpenDDSharp.zip)
